# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 5 * * 1-4"   # Schedule for 6:00am every Monday
  displayName: "Run Pipeline every Monday - Thursday at 6:00am"
  branches:
    include:
    - master  # Replace with the branch you want to build
trigger:
  branches:
    include:
      - master
pool:
  vmImage: ubuntu-latest

variables:
  - name: endpointUrl
    value: https://www.blazingchat.com
  - name: insecureSsl
    value: true

steps:                   
- task: Npm@1
  displayName: 'Install Playwright'
  inputs:
      command: 'custom'
      customCommand: 'npm install '
      
- task: Bash@3
  displayName: Run Playwright tests
  inputs:
          targetType: inline
          failOnStderr: true
          env:
          CI: true
          script: |
               npx playwright install && npm run playwright$(appNameTest)-integration-test

- task: PublishTestResults@2
  displayName: 'Playwright Test results'
  condition: succeededOrFailed()
  inputs:
      testRunTitle: DEV_Playwright_TESTS
      testResultsFormat: JUnit
      testResultsFiles: '**/*.xml'
      mergeTestResults: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish HTML Report'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/.azurepipeline/testcases/postman/report'
    ArtifactName: 'Report'
